"""add_views_number

Revision ID: eef1a03d7d45
Revises: d2f92c9402e0
Create Date: 2022-12-13 16:03:59.655650

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "eef1a03d7d45"
down_revision = "d2f92c9402e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq__film__id"), "film", ["id"])
    op.create_unique_constraint(op.f("uq__search_history__id"), "search_history", ["id"])
    op.add_column("user_film_view", sa.Column("views", sa.Integer(), server_default=sa.text("0"), nullable=True))
    op.create_unique_constraint(op.f("uq__user_film_view__id"), "user_film_view", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq__user_film_view__id"), "user_film_view", type_="unique")
    op.drop_column("user_film_view", "views")
    op.drop_constraint(op.f("uq__search_history__id"), "search_history", type_="unique")
    op.drop_constraint(op.f("uq__film__id"), "film", type_="unique")
    # ### end Alembic commands ###
