"""initial

Revision ID: 36cfd7d71076
Revises:
Create Date: 2025-04-09 15:38:04.489664

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "36cfd7d71076"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "film",
        sa.Column("name_ru", sa.TEXT(), nullable=False),
        sa.Column("name_eng", sa.TEXT(), nullable=False),
        sa.Column("kinopoisk_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_film")),
        sa.UniqueConstraint("id", name=op.f("uq_film_id")),
    )
    op.create_index(op.f("ix_film_kinopoisk_id"), "film", ["kinopoisk_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_table(
        "search_history",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("request_text", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_search_history_user_id_user"), onupdate="CASCADE", ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_history")),
        sa.UniqueConstraint("id", name=op.f("uq_search_history_id")),
    )
    op.create_index(op.f("ix_search_history_user_id"), "search_history", ["user_id"], unique=False)
    op.create_table(
        "user_film_view",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("film_id", sa.UUID(), nullable=False),
        sa.Column("views", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["film_id"], ["film.id"], name=op.f("fk_user_film_view_film_id_film"), onupdate="CASCADE", ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_user_film_view_user_id_user"), onupdate="CASCADE", ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_film_view")),
        sa.UniqueConstraint("id", name=op.f("uq_user_film_view_id")),
    )
    op.create_index(op.f("ix_user_film_view_film_id"), "user_film_view", ["film_id"], unique=False)
    op.create_index(op.f("ix_user_film_view_user_id"), "user_film_view", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_film_view_user_id"), table_name="user_film_view")
    op.drop_index(op.f("ix_user_film_view_film_id"), table_name="user_film_view")
    op.drop_table("user_film_view")
    op.drop_index(op.f("ix_search_history_user_id"), table_name="search_history")
    op.drop_table("search_history")
    op.drop_table("user")
    op.drop_index(op.f("ix_film_kinopoisk_id"), table_name="film")
    op.drop_table("film")
    # ### end Alembic commands ###
