name: Linters and tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v4
      - id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
          enable-cache: true
      - name: Install dependencies
        if: steps.setup-uv.outputs.cache-hit != 'true'
        run: uv sync --all-extras
      - name: Run tests
        run: uv run pytest
